version: "3"

services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "nginxConf:/etc/nginx/conf.d"
      - "nginxVhosts:/etc/nginx/vhost.d"
      - "nginxHtml:/usr/share/nginx/html:ro"
      - "certs:/etc/nginx/certs:ro"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "nginxConf:/etc/nginx/conf.d"
      - "nginxVhosts:/etc/nginx/vhost.d"
      - "nginxHtml:/usr/share/nginx/html"
      - "certs:/etc/nginx/certs:rw"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  portainer:
    image: portainer/portainer
    depends_on:
      - nginx
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainerData:/data"
    environment: 
      - VIRTUAL_HOST=portainer.lordvlad.tk
      - LETSENCRYPT_HOST=portainer.lordvlad.tk
      - LETSENCRYPT_EMAIL=waldemar.reusch@googlemail.com
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  verdaccio:
    image: lordvlad/verdaccio
    depends_on:
      - nginx
    ports:
      - "4873:4873"
    volumes:
      - "verdaccioData:/verdaccio"
    environment:
      - VIRTUAL_HOST=verdaccio.lordvlad.tk
      - LETSENCRYPT_HOST=verdaccio.lordvlad.tk
      - LETSENCRYPT_EMAIL=waldemar.reusch@googlemail.com
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  verdaccioData: {}
  portainerData: {}
  nginxVhosts: {}
  nginxConf: {}
  nginxHtml: {}
  certs: {}
