version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginxConf:/etc/nginx/conf.d:ro"
      - "nginxVhosts:/etc/nginx/vhost.d:ro"
      - "nginxHtml:/usr/share/nginx/html:ro"
      - "certs:/etc/nginx/certs:ro"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    networks:
      - stack
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx-gen:
    image: jwilder/docker-gen
    depends_on:
      - nginx
    command: -notify-sighup -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./docker-gen/templates:/etc/docker-gen/templates:ro"
      - "nginxConf:/etc/nginx/conf.d"
      - "nginxVhosts:/etc/nginx/vhost.d"
      - "nginxHtml:/usr/share/nginx/html"
      - "certs:/etc/nginx/certs:ro"
    networks:
      - stack
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-gen
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "nginxConf:/etc/nginx/conf.d"
      - "nginxVhosts:/etc/nginx/vhost.d"
      - "nginxHtml:/usr/share/nginx/html"
      - "certs:/etc/nginx/certs:rw"
#     environment:
#       - "NGINX_DOCKER_GEN_CONTAINER=stack_nginx-gen_1" 
    networks:
      - stack
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  portainer:
    image: portainer/portainer
    depends_on:
      - nginx-gen
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainerData:/data"
    environment: 
      - VIRTUAL_HOST=portainer.${DOMAIN}
      - LETSENCRYPT_HOST=portainer.${DOMAIN}
      - LETSENCRYPT_EMAIL=${E_MAIL}
    networks:
      - stack
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  verdaccio:
    image: lordvlad/verdaccio
    depends_on:
      - nginx-gen
    ports:
      - "4873:4873"
    environment: 
      - VIRTUAL_HOST=verdaccio.${DOMAIN}
      - LETSENCRYPT_HOST=verdaccio.${DOMAIN}
      - LETSENCRYPT_EMAIL=${E_MAIL}
    networks:
      - stack
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  stack: {}

volumes:
  portainerData: {}
  nginxVhosts: {}
  nginxData: {}
  nginxConf: {}
  nginxHtml: {}
  certs: {}
